#include "c_emitter.h"
#include "peg_engine.h"
#include "header_engine.h"
#include <sstream>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <filesystem>

namespace alphabet {
namespace forge {

namespace {

class CAstVisitor {
public:
    explicit CAstVisitor(const ForgeSpec& spec) : spec_(spec), indent_level_(1) {}

    std::string emit_program(const std::vector<alphabet::StmtPtr>& stmts) {
        std::ostringstream ss;
        // Runtime header
        ss << "/* Generated by Alphabet Forge for " << spec_.name << " v" << spec_.version << " */\n";
        ss << "#include <stdio.h>\n";
        ss << "#include <stdlib.h>\n";
        ss << "#include <string.h>\n";
        ss << "#include <stdbool.h>\n";
        ss << "#include <stdint.h>\n\n";

        // Minimal dynamic value runtime
        ss << "typedef enum { VAL_NIL, VAL_BOOL, VAL_NUM, VAL_STR } ValType;\n";
        ss << "typedef struct {\n";
        ss << "    ValType type;\n";
        ss << "    union {\n";
        ss << "        bool boolean;\n";
        ss << "        double num;\n";
        ss << "        char* str;\n";
        ss << "    } as;\n";
        ss << "} Value;\n\n";

        ss << "static Value make_num(double n) { Value v; v.type = VAL_NUM; v.as.num = n; return v; }\n";
        ss << "static Value make_bool(bool b) { Value v; v.type = VAL_BOOL; v.as.boolean = b; return v; }\n";
        ss << "static Value make_str(const char* s) { Value v; v.type = VAL_STR; v.as.str = strdup(s ? s : \"\"); return v; }\n";
        ss << "static Value make_nil() { Value v; v.type = VAL_NIL; return v; }\n\n";

        ss << "static void print_val(Value v) {\n";
        ss << "    if (v.type == VAL_NUM) {\n";
        ss << "        if ((int64_t)v.as.num == v.as.num) printf(\"%lld\\n\", (long long)v.as.num);\n";
        ss << "        else printf(\"%g\\n\", v.as.num);\n";
        ss << "    } else if (v.type == VAL_STR) {\n";
        ss << "        printf(\"%s\\n\", v.as.str ? v.as.str : \"\");\n";
        ss << "    } else if (v.type == VAL_BOOL) {\n";
        ss << "        printf(\"%s\\n\", v.as.boolean ? \"true\" : \"false\");\n";
        ss << "    } else {\n";
        ss << "        printf(\"nil\\n\");\n";
        ss << "    }\n";
        ss << "}\n\n";

        ss << "static Value val_add(Value a, Value b) {\n";
        ss << "    if (a.type == VAL_NUM && b.type == VAL_NUM) return make_num(a.as.num + b.as.num);\n";
        ss << "    if (a.type == VAL_STR && b.type == VAL_STR) {\n";
        ss << "        size_t la = strlen(a.as.str), lb = strlen(b.as.str);\n";
        ss << "        char* buf = (char*)malloc(la + lb + 1);\n";
        ss << "        strcpy(buf, a.as.str); strcat(buf, b.as.str);\n";
        ss << "        Value v; v.type = VAL_STR; v.as.str = buf; return v;\n";
        ss << "    }\n";
        ss << "    return make_num(0);\n";
        ss << "}\n";
        ss << "static Value val_sub(Value a, Value b) { return make_num(a.as.num - b.as.num); }\n";
        ss << "static Value val_mul(Value a, Value b) { return make_num(a.as.num * b.as.num); }\n";
        ss << "static Value val_div(Value a, Value b) { return make_num(b.as.num != 0.0 ? a.as.num / b.as.num : 0.0); }\n";
        ss << "static bool val_is_truthy(Value v) {\n";
        ss << "    if (v.type == VAL_BOOL) return v.as.boolean;\n";
        ss << "    if (v.type == VAL_NUM) return v.as.num != 0.0;\n";
        ss << "    if (v.type == VAL_STR) return v.as.str && strlen(v.as.str) > 0;\n";
        ss << "    return false;\n";
        ss << "}\n";
        ss << "static Value val_eq(Value a, Value b) {\n";
        ss << "    if (a.type != b.type) return make_bool(false);\n";
        ss << "    if (a.type == VAL_NUM) return make_bool(a.as.num == b.as.num);\n";
        ss << "    if (a.type == VAL_BOOL) return make_bool(a.as.boolean == b.as.boolean);\n";
        ss << "    if (a.type == VAL_STR) return make_bool(strcmp(a.as.str, b.as.str) == 0);\n";
        ss << "    return make_bool(true);\n";
        ss << "}\n";
        ss << "static Value val_lt(Value a, Value b) { return make_bool(a.as.num < b.as.num); }\n";
        ss << "static Value val_gt(Value a, Value b) { return make_bool(a.as.num > b.as.num); }\n";
        ss << "static Value val_lte(Value a, Value b) { return make_bool(a.as.num <= b.as.num); }\n";
        ss << "static Value val_gte(Value a, Value b) { return make_bool(a.as.num >= b.as.num); }\n\n";

        // Separate function declarations from main statements
        std::vector<alphabet::StmtPtr> fn_stmts;
        std::vector<alphabet::StmtPtr> main_stmts;
        for (const auto& s : stmts) {
            if (dynamic_cast<alphabet::FunctionStmt*>(s.get())) {
                fn_stmts.push_back(s);
            } else {
                main_stmts.push_back(s);
            }
        }

        for (const auto& fn : fn_stmts) {
            ss << emit_stmt(fn) << "\n";
        }

        ss << "int main(int argc, char** argv) {\n";
        ss << "    (void)argc; (void)argv;\n";
        for (const auto& s : main_stmts) {
            ss << emit_stmt(s);
        }
        ss << "    return 0;\n";
        ss << "}\n";

        return ss.str();
    }

private:
    const ForgeSpec& spec_;
    int indent_level_;

    std::string indent() const {
        return std::string(indent_level_ * 4, ' ');
    }

    std::string emit_stmt(const alphabet::StmtPtr& stmt) {
        if (!stmt) return "";

        if (auto* var_stmt = dynamic_cast<alphabet::VarStmt*>(stmt.get())) {
            std::ostringstream ss;
            ss << indent() << "Value " << var_stmt->name.lexeme << " = ";
            if (var_stmt->initializer) {
                ss << emit_expr(var_stmt->initializer);
            } else {
                ss << "make_nil()";
            }
            ss << ";\n";
            return ss.str();
        }

        if (auto* expr_stmt = dynamic_cast<alphabet::ExpressionStmt*>(stmt.get())) {
            // Check if calling z.o(expr) which is print
            if (auto* call = dynamic_cast<alphabet::Call*>(expr_stmt->expression.get())) {
                if (auto* get = dynamic_cast<alphabet::Get*>(call->callee.get())) {
                    if (get->name.lexeme == "o") {
                        std::ostringstream ss;
                        ss << indent() << "print_val(";
                        if (!call->arguments.empty()) {
                            ss << emit_expr(call->arguments[0]);
                        } else {
                            ss << "make_nil()";
                        }
                        ss << ");\n";
                        return ss.str();
                    }
                }
            }
            return indent() + emit_expr(expr_stmt->expression) + ";\n";
        }

        if (auto* if_stmt = dynamic_cast<alphabet::IfStmt*>(stmt.get())) {
            std::ostringstream ss;
            ss << indent() << "if (val_is_truthy(" << emit_expr(if_stmt->condition) << ")) {\n";
            indent_level_++;
            ss << emit_stmt(if_stmt->then_branch);
            indent_level_--;
            if (if_stmt->else_branch) {
                ss << indent() << "} else {\n";
                indent_level_++;
                ss << emit_stmt(if_stmt->else_branch);
                indent_level_--;
            }
            ss << indent() << "}\n";
            return ss.str();
        }

        if (auto* loop = dynamic_cast<alphabet::LoopStmt*>(stmt.get())) {
            std::ostringstream ss;
            ss << indent() << "while (val_is_truthy(" << emit_expr(loop->condition) << ")) {\n";
            indent_level_++;
            ss << emit_stmt(loop->body);
            indent_level_--;
            ss << indent() << "}\n";
            return ss.str();
        }

        if (auto* blk = dynamic_cast<alphabet::Block*>(stmt.get())) {
            std::ostringstream ss;
            for (const auto& s : blk->statements) {
                ss << emit_stmt(s);
            }
            return ss.str();
        }

        if (auto* fn = dynamic_cast<alphabet::FunctionStmt*>(stmt.get())) {
            std::ostringstream ss;
            ss << "Value " << fn->name.lexeme << "(";
            for (size_t i = 0; i < fn->params.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << "Value " << fn->params[i].name.lexeme;
            }
            ss << ") {\n";
            indent_level_++;
            for (const auto& s : fn->body) {
                ss << emit_stmt(s);
            }
            ss << indent() << "return make_nil();\n";
            indent_level_--;
            ss << "}\n";
            return ss.str();
        }

        if (auto* ret = dynamic_cast<alphabet::ReturnStmt*>(stmt.get())) {
            std::ostringstream ss;
            ss << indent() << "return " << (ret->value ? emit_expr(ret->value) : "make_nil()") << ";\n";
            return ss.str();
        }

        return "";
    }

    std::string emit_expr(const alphabet::ExprPtr& expr) {
        if (!expr) return "make_nil()";

        if (auto* lit = dynamic_cast<alphabet::Literal*>(expr.get())) {
            if (std::holds_alternative<int64_t>(lit->value)) {
                return "make_num(" + std::to_string(std::get<int64_t>(lit->value)) + ")";
            }
            if (std::holds_alternative<double>(lit->value)) {
                return "make_num(" + std::to_string(std::get<double>(lit->value)) + ")";
            }
            if (std::holds_alternative<std::string>(lit->value)) {
                std::string raw = std::get<std::string>(lit->value);
                std::string esc;
                for (char c : raw) {
                    if (c == '"') esc += "\\\"";
                    else if (c == '\\') esc += "\\\\";
                    else if (c == '\n') esc += "\\n";
                    else if (c == '\t') esc += "\\t";
                    else esc += c;
                }
                return "make_str(\"" + esc + "\")";
            }
            return "make_nil()";
        }

        if (auto* var = dynamic_cast<alphabet::Variable*>(expr.get())) {
            return std::string(var->name.lexeme);
        }

        if (auto* assign = dynamic_cast<alphabet::Assign*>(expr.get())) {
            return "(" + std::string(assign->name.lexeme) + " = " + emit_expr(assign->value) + ")";
        }

        if (auto* bin = dynamic_cast<alphabet::Binary*>(expr.get())) {
            std::string l = emit_expr(bin->left);
            std::string r = emit_expr(bin->right);
            switch (bin->op.type) {
                case alphabet::TokenType::PLUS: return "val_add(" + l + ", " + r + ")";
                case alphabet::TokenType::MINUS: return "val_sub(" + l + ", " + r + ")";
                case alphabet::TokenType::STAR: return "val_mul(" + l + ", " + r + ")";
                case alphabet::TokenType::SLASH: return "val_div(" + l + ", " + r + ")";
                case alphabet::TokenType::DOUBLE_EQUALS: return "val_eq(" + l + ", " + r + ")";
                case alphabet::TokenType::NOT_EQUALS: return "make_bool(!val_is_truthy(val_eq(" + l + ", " + r + ")))";
                case alphabet::TokenType::LESS: return "val_lt(" + l + ", " + r + ")";
                case alphabet::TokenType::LESS_EQUALS: return "val_lte(" + l + ", " + r + ")";
                case alphabet::TokenType::GREATER: return "val_gt(" + l + ", " + r + ")";
                case alphabet::TokenType::GREATER_EQUALS: return "val_gte(" + l + ", " + r + ")";
                default: return "val_add(" + l + ", " + r + ")";
            }
        }

        if (auto* un = dynamic_cast<alphabet::Unary*>(expr.get())) {
            std::string inner = emit_expr(un->right);
            if (un->op.type == alphabet::TokenType::MINUS) {
                return "make_num(-(" + inner + ").as.num)";
            }
            if (un->op.type == alphabet::TokenType::NOT) {
                return "make_bool(!val_is_truthy(" + inner + "))";
            }
        }

        if (auto* grp = dynamic_cast<alphabet::Grouping*>(expr.get())) {
            return "(" + emit_expr(grp->expression) + ")";
        }

        if (auto* call = dynamic_cast<alphabet::Call*>(expr.get())) {
            std::ostringstream ss;
            ss << emit_expr(call->callee) << "(";
            for (size_t i = 0; i < call->arguments.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << emit_expr(call->arguments[i]);
            }
            ss << ")";
            return ss.str();
        }

        return "make_nil()";
    }
};

} // namespace

std::string ForgeCEmitter::emit_c(const std::vector<alphabet::StmtPtr>& statements, const ForgeSpec& spec) {
    CAstVisitor visitor(spec);
    return visitor.emit_program(statements);
}

bool ForgeCEmitter::compile_to_native(const std::string& source,
                                      const ForgeSpec& spec,
                                      const std::string& output_binary,
                                      std::string& out_error,
                                      bool keep_c_source,
                                      const std::string& target_triple) {
    // 1. Process header
    HeaderParseResult hdr = HeaderEngine::parse(source, spec.header, spec.name);
    if (!hdr.valid) {
        out_error = hdr.error;
        return false;
    }

    // 2. Parse PEG grammar to AST
    PegEngine peg(spec);
    ParseResult parse_res = peg.parse(hdr.stripped_source, output_binary, hdr.header_lines);
    if (!parse_res.success) {
        out_error = parse_res.errors.empty() ? "Parse error" : parse_res.errors[0].format(output_binary);
        return false;
    }

    // 3. Emit C source code
    std::string c_code = emit_c(parse_res.statements, spec);

    std::string c_file = output_binary + ".c";
    std::ofstream out(c_file);
    if (!out.is_open()) {
        out_error = "Could not write temporary C file: " + c_file;
        return false;
    }
    out << c_code;
    out.close();

    // 4. Determine C compiler and flags
    std::string compiler = "gcc";
    std::string extra_flags = "-lm";
    std::string final_out = output_binary;

    if (!target_triple.empty() && target_triple != "native" && target_triple != "bytecode" && target_triple != "interpreted") {
        if (target_triple == "wasm" || target_triple == "wasm32" || target_triple == "emscripten") {
            if (std::system("which emcc > /dev/null 2>&1") == 0) {
                compiler = "emcc";
                extra_flags = "-s WASM=1 -s ALLOW_MEMORY_GROWTH=1";
                if (final_out.find(".html") == std::string::npos && 
                    final_out.find(".js") == std::string::npos && 
                    final_out.find(".wasm") == std::string::npos) {
                    final_out += ".html";
                }
            } else {
                out_error = "Emscripten (emcc) not found on system. To build WebAssembly, please install emsdk.";
                return false;
            }
        } else {
            // Windows target check
            if (target_triple.find("mingw") != std::string::npos || target_triple.find("windows") != std::string::npos) {
                if (final_out.size() < 4 || final_out.substr(final_out.size() - 4) != ".exe") {
                    final_out += ".exe";
                }
            }
            std::string cross_gcc = target_triple + "-gcc";
            std::string check_cmd = "which " + cross_gcc + " > /dev/null 2>&1";
            if (std::system(check_cmd.c_str()) == 0) {
                compiler = cross_gcc;
            } else if (std::system("which clang > /dev/null 2>&1") == 0) {
                compiler = "clang --target=" + target_triple;
            } else {
                out_error = "Cross-compiler not found for target '" + target_triple + "'. Please install " + cross_gcc + " or clang.";
                return false;
            }
        }
    } else {
        if (std::system("which gcc > /dev/null 2>&1") != 0) {
            if (std::system("which clang > /dev/null 2>&1") == 0) {
                compiler = "clang";
            } else {
                out_error = "Neither gcc nor clang found on system to compile native binary";
                return false;
            }
        }
    }

    std::string cmd = compiler + " -O2 \"" + c_file + "\" " + extra_flags + " -o \"" + final_out + "\"";
    int res = std::system(cmd.c_str());
    if (res != 0) {
        out_error = "Compilation command failed: " + cmd;
        return false;
    }

    if (!keep_c_source) {
        std::filesystem::remove(c_file);
    }

    return true;
}

} // namespace forge
} // namespace alphabet
